import LegalDocumentLayout from "components/LegalDocumentLayout";
import Link from "@mui/material/Link";
import Box from "@mui/material/Box";
import PropTypes from "prop-types";

/* ── Design tokens (mirror Privacy.jsx) ───────────────────────────────── */
const NAVY   = "#0d1b2a";
const BODY   = "#1f2937";
const SUBTLE = "#4b5563";
const RULE   = "#e2e5ea";
const ACCENT = "#c9a84c";
const FS     = 13.5;

const P = (props) => (
  <Box component="p" sx={{ fontSize: FS, lineHeight: 1.85, color: BODY, fontFamily: "inherit", m: 0, mb: "0.75rem" }} {...props} />
);

const Bullets = ({ items }) => (
  <Box component="ul" sx={{ m: 0, pl: "1.5rem", mb: "0.9rem" }}>
    {items.map((item, i) => (
      <Box component="li" key={i} sx={{ fontSize: FS, lineHeight: 1.85, color: BODY, fontFamily: "inherit", mb: "0.3rem" }}>
        {item}
      </Box>
    ))}
  </Box>
);
Bullets.propTypes = { items: PropTypes.arrayOf(PropTypes.node).isRequired };

const SectionHeading = ({ children }) => (
  <Box sx={{ mt: "2rem", mb: "0.75rem" }}>
    <Box component="h3" sx={{ fontSize: 10, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.18em", color: SUBTLE, fontFamily: "inherit", m: 0, mb: "0.45rem" }}>
      {children}
    </Box>
    <Box sx={{ height: "1px", background: RULE, width: "100%" }} />
  </Box>
);
SectionHeading.propTypes = { children: PropTypes.node.isRequired };

const SubHeading = ({ children }) => (
  <Box component="h4" sx={{ fontSize: FS, fontWeight: 700, color: NAVY, fontFamily: "inherit", m: 0, mt: "1.1rem", mb: "0.4rem" }}>
    {children}
  </Box>
);
SubHeading.propTypes = { children: PropTypes.node.isRequired };

const D = () => <Box sx={{ mt: "0.25rem" }} />;

const A = ({ href, children }) => (
  <Link href={href} sx={{ color: NAVY, fontWeight: 600, fontSize: FS, textDecoration: "none", borderBottom: `1px solid ${ACCENT}`, pb: "1px", "&:hover": { borderBottomColor: NAVY } }}>
    {children}
  </Link>
);
A.propTypes = { href: PropTypes.string.isRequired, children: PropTypes.node.isRequired };



export default function Terms() {
  return (
    <LegalDocumentLayout title="Terms of Use" effectiveDate="February 18, 2026" hideMetadata>

      <P>These Terms of Use (&ldquo;Terms&rdquo;) govern your access to and use of LookThroughProfits.com, stockownerreport.com, and any related websites, applications, products, and services offered by LookThroughProfits, Inc. (collectively, the &ldquo;Service&rdquo;).</P>
      <P><strong>PLEASE READ THESE TERMS CAREFULLY.</strong> By creating an account, accessing, or using the Service, you agree to these Terms. If you do not agree, do not use the Service.</P>

      <D />
      <SectionHeading>Key Points (Non-Binding Summary)</SectionHeading>
      <P sx={{ fontSize: 12, color: SUBTLE, mb: "0.5rem" }}>This summary is for convenience only and does not change the meaning of these Terms.</P>
      <Bullets items={[
        "The Service provides portfolio analytics and reporting for informational and educational purposes and is not investment advice.",
        "The Service depends on third-party providers (including brokerage connectivity providers) and may be delayed, incomplete, or unavailable.",
        "If you connect a brokerage account, you authorize data access to generate reports; you remain responsible for your investment decisions and brokerage activity.",
        "Your use of the Service is subject to important disclaimers, limitations of liability, and dispute-resolution terms, with jurisdiction-specific consumer rights preserved where required by law.",
      ]} />

      <D />
      <SectionHeading>Definitions</SectionHeading>
      <Bullets items={[
        <><strong>&ldquo;Content&rdquo;</strong> means any text, graphics, images, videos, software, tools, calculations, models, templates, reports, and other materials made available through the Service.</>,
        <><strong>&ldquo;Report&rdquo;</strong> means any output, analysis, dashboard, chart, portfolio &ldquo;owner&rsquo;s view,&rdquo; pro-rata/&ldquo;look-through&rdquo; metrics, or similar output generated by the Service.</>,
        <><strong>&ldquo;Brokerage Connection&rdquo;</strong> means a connection to a brokerage or financial institution account established through a third-party connectivity provider integrated into the Service.</>,
        <><strong>&ldquo;User&rdquo; / &ldquo;you&rdquo;</strong> means the individual or entity using the Service.</>,
      ]} />

      <D />
      <SectionHeading>Eligibility and Account Registration</SectionHeading>
      <P>You represent and warrant that:</P>
      <Bullets items={[
        "You are at least 18 years old (or the age of majority where you live, if higher).",
        "You have the legal capacity to enter into these Terms.",
        "If you use the Service on behalf of an organization, you have authority to bind that organization, and \u201cyou\u201d includes the organization.",
      ]} />
      <P>To use certain features, you must create an account. You agree to:</P>
      <Bullets items={[
        "Provide accurate, current, and complete information;",
        "Maintain the confidentiality of your login credentials; and",
        "Be responsible for all activity under your account.",
      ]} />
      <P>We may suspend or terminate your account as described below.</P>

      <D />
      <SectionHeading>The Service</SectionHeading>

      <SubHeading>What the Service does</SubHeading>
      <P>The Service turns a brokerage portfolio into an &ldquo;owner&rsquo;s view&rdquo; by translating holdings into business-level metrics and portfolio-level presentations (for example, look-through estimates of revenue, operating profit, assets, liabilities, and similar lines) based on your holdings and financial/fundamental data sources.</P>

      <SubHeading>No brokerage services; no trading; no custody</SubHeading>
      <P>The Service does not function as a brokerage, trading venue, or custodian.</P>
      <Bullets items={[
        "We do not execute trades on your behalf through the Service.",
        "We do not take custody of your assets or funds.",
        "We do not provide account administration services for your brokerage account(s).",
      ]} />

      <SubHeading>Not investment advice; not a fiduciary</SubHeading>
      <P>The Service is provided for informational and educational purposes only.</P>
      <Bullets items={[
        "We are not your investment adviser, broker-dealer, commodity trading advisor, financial planner, or fiduciary.",
        "Nothing in the Service constitutes investment, financial, tax, accounting, or legal advice.",
        "The Service does not provide personalized recommendations, and we do not consider your individual circumstances (e.g., financial situation, risk tolerance, investment objectives) when generating Reports unless explicitly stated otherwise.",
        "You are solely responsible for your investment decisions, including whether to buy, sell, hold, or not buy/sell any security or other asset.",
        "You should consult qualified professionals before making financial decisions.",
      ]} />
      <P><strong>Important investing risk disclosures:</strong> Investing involves risk, including the possible loss of some or all of your investment. Past performance is not a guarantee of future performance. You should consider whether any investment, strategy, or portfolio decision is appropriate for you.</P>

      <D />
      <SectionHeading>Brokerage Connections and Third-Party Providers</SectionHeading>

      <SubHeading>Third-party connectivity provider</SubHeading>
      <P>If the Service offers the ability to connect a brokerage account, the connection is facilitated by a third-party brokerage connectivity provider. We currently use SnapTrade to facilitate brokerage connections.</P>
      <P>You understand and agree that:</P>
      <Bullets items={[
        "The brokerage connectivity provider is a third party that operates independently of us.",
        "The ability to connect accounts, the availability of brokerages, and the completeness and timeliness of returned data depend on third parties (including the connectivity provider and the brokerage/financial institution).",
      ]} />

      <SubHeading>Your authorization; your responsibility</SubHeading>
      <P>When you initiate and complete a Brokerage Connection, you authorize us (and our connectivity provider) to access the account data you permit and to use that data to provide the Service, including generating Reports.</P>
      <P>You represent and warrant that:</P>
      <Bullets items={[
        "You are the authorized owner of the brokerage account(s) you connect, or you are otherwise authorized to connect and share data from those account(s); and",
        "All data you provide or authorize us to access is accurate to the best of your knowledge.",
      ]} />

      <SubHeading>Reauthorizations; broken connections; stale data</SubHeading>
      <P>Brokerage connections can fail or be disabled for security reasons, and may require reauthorization. Data delivered via third parties may be cached, delayed, incomplete, or unavailable from time to time.</P>
      <P>We are not responsible for:</P>
      <Bullets items={[
        "Any inability to connect to a brokerage;",
        "Any failure, delay, or outage of a brokerage, connectivity provider, or related third-party service; or",
        "Any decisions you make based on data that is delayed, incomplete, or inaccurate.",
      ]} />

      <SubHeading>Third-party terms apply (including SnapTrade terms)</SubHeading>
      <P>Your use of brokerage connectivity features may require you to accept additional third-party terms, including the connectivity provider&rsquo;s end-user terms and privacy policy. If those terms conflict with these Terms regarding operation of the third-party service, the third-party terms govern as to that third-party service.</P>
      <P>If you do not agree to the required third-party terms, do not use the brokerage connectivity feature.</P>

      <D />
      <SectionHeading>Reports, Calculations, and Data Limitations</SectionHeading>
      <P>You acknowledge and agree that:</P>
      <Bullets items={[
        "Reports and calculations may rely on third-party data sources, public filings, licensed datasets, and/or automated extraction and normalization processes.",
        "Reports include estimates, assumptions, and methodological choices (for example, pro-rata/\u201clook-through\u201d allocations based on share counts and financial statement lines) and may not match audited financial statements, broker statements, or any third-party report.",
        "Corporate actions, restatements, delayed filings, symbol changes, currency conversions, and data vendor differences can affect results.",
        "The Service may display \u201cas of\u201d dates and may not reflect real-time holdings or real-time market conditions.",
        "You agree not to treat Reports as definitive or error-free and to independently verify information as appropriate.",
      ]} />

      <D />
      <SectionHeading>Data Source and Disclaimer</SectionHeading>
      <P>Stock Owner Report uses company financial data provided by SimFin. The data is refreshed every night to help provide users with current and useful financial information.</P>
      <P>Financial statement data, including balance sheet and income statement information, is generally based on the company&rsquo;s most recently available fiscal year-end data from SimFin. For example, if a report is generated on March 31, 2026, the report may use financial statement data for the fiscal year ending December 31, 2025, if that is the latest year-end data available from SimFin.</P>
      <P>Stock Owner Report makes reasonable efforts to provide accurate, complete, and up-to-date information. However, Stock Owner Report does not guarantee the accuracy, completeness, timeliness, or reliability of any data, calculations, reports, summaries, or analysis generated by the platform.</P>
      <P>Users are responsible for independently verifying all information before making any investment, financial, tax, legal, or business decision. Reports generated by Stock Owner Report are provided for informational and analytical purposes only and should not be relied upon as financial advice, investment advice, or a recommendation to buy, sell, or hold any security.</P>
      <P>By using Stock Owner Report, the user agrees to indemnify and hold harmless Stock Owner Report, its owners, managers, officers, employees, contractors, affiliates, and service providers from any claims, losses, damages, liabilities, costs, or expenses arising from or related to decisions made based on information, reports, calculations, or analysis generated by Stock Owner Report, including where such information may be incorrect, incomplete, delayed, or outdated.</P>

      <D />
      <SectionHeading>Acceptable Use and Restrictions</SectionHeading>
      <P>You agree that you will not (and will not attempt to):</P>
      <Bullets items={[
        "Reverse engineer, decompile, disassemble, or otherwise attempt to discover the source code or underlying ideas of the Service (except to the extent such restriction is prohibited by law);",
        "Copy, reproduce, redistribute, resell, lease, or commercially exploit the Service or Content, except as expressly permitted by these Terms;",
        "Use the Service to create a competing product or service, or to benchmark the Service in a way intended for publication or competitive use without our written consent;",
        "Scrape, crawl, or use automated means to access the Service except through interfaces we explicitly provide;",
        "Interfere with or disrupt the integrity or performance of the Service, including by probing, scanning, or testing the vulnerability of any system or network (unless we have expressly authorized such testing in writing);",
        "Use the Service for unlawful, fraudulent, deceptive, or harmful purposes; or",
        "Use the Service in a way that violates any law, regulation, or third-party rights (including data licensing restrictions).",
      ]} />
      <P>We may investigate violations and may suspend or terminate access as described below.</P>

      <D />
      <SectionHeading>Intellectual Property</SectionHeading>
      <P>The Service, including all Content and underlying software, is owned by LookThroughProfits, Inc. and/or our licensors and is protected by intellectual property laws.</P>
      <P>Subject to your compliance with these Terms, we grant you a limited, revocable, non-exclusive, non-transferable, non-sublicensable license to access and use the Service for your personal use or internal business purposes (as applicable), during the term of your subscription or authorized access.</P>
      <P>All rights not expressly granted are reserved.</P>

      <D />
      <SectionHeading>Feedback</SectionHeading>
      <P>If you submit feedback, suggestions, or ideas about the Service, you grant us a perpetual, irrevocable, worldwide, royalty-free license to use, modify, and incorporate that feedback without restriction or compensation to you.</P>

      <D />
      <SectionHeading>Subscriptions, Billing, and Taxes</SectionHeading>

      <SubHeading>Billing and payment processing</SubHeading>
      <P>Certain Service features require payment of subscription fees. Payments are processed via third-party payment processors, including Stripe. By purchasing a subscription, you authorize us (and our payment processors) to charge your selected payment method on a recurring basis until you cancel, and you agree to pay all applicable fees and taxes.</P>

      <SubHeading>Renewal</SubHeading>
      <P>Subscriptions typically renew automatically unless you cancel before the renewal date. The renewal cadence, price, and renewal date will be disclosed at the time of checkout and/or in your account.</P>

      <SubHeading>Cancellation</SubHeading>
      <P>You can cancel your subscription by following the cancellation instructions in your account settings or by contacting us at <A href="mailto:howard@stockownerreport.com">howard@stockownerreport.com</A>. Cancellation stops future renewals; you will retain access through the end of the then-current paid period unless otherwise stated.</P>

      <SubHeading>Refunds</SubHeading>
      <P>Fees are non-refundable and non-creditable except where required by law or as expressly stated in writing by us.</P>

      <SubHeading>Price changes</SubHeading>
      <P>We may change pricing, plans, or features from time to time. If we make a material pricing change affecting your subscription, we will provide reasonable notice (for example, via email or in-product notice). Continued use after the change takes effect constitutes acceptance of the updated pricing, to the extent permitted by law.</P>

      <D />
      <SectionHeading>Privacy</SectionHeading>
      <P>Our collection and use of personal information is described in our Privacy Policy, which is incorporated into these Terms by reference. In the event of a conflict between these Terms and the Privacy Policy regarding the processing of personal information, the Privacy Policy controls.</P>

      <D />
      <SectionHeading>Suspension and Termination</SectionHeading>
      <P>We may suspend or terminate your access to the Service (including your account) immediately, with or without notice, if:</P>
      <Bullets items={[
        "You violate these Terms;",
        "We reasonably believe your use poses a security risk, legal risk, or risk to other users; or",
        "We are required to do so to comply with law or the requirements of third-party providers.",
      ]} />
      <P>You may terminate your account at any time by canceling your subscription and requesting account deletion (subject to lawful retention obligations).</P>
      <P>Upon termination:</P>
      <Bullets items={[
        "Your license to use the Service ends immediately;",
        "We may disable your access to the Service and Reports; and",
        "Certain provisions of these Terms survive, including (as applicable) intellectual property, disclaimers, limitation of liability, indemnification, and dispute resolution.",
      ]} />

      <D />
      <SectionHeading>Disclaimers</SectionHeading>
      <P>The Service is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis. To the maximum extent permitted by law, LookThroughProfits, Inc. disclaims all warranties and conditions, whether express, implied, or statutory, including any implied warranties of merchantability, fitness for a particular purpose, title, non-infringement, and any warranties arising from course of dealing or usage of trade.</P>
      <P>We do not warrant that the Service will be accurate, complete, reliable, error-free, secure, or uninterrupted, or that any defects will be corrected.</P>
      <P>We do not warrant that Reports or data will be real-time or that any output will match third-party sources (including broker statements or data providers).</P>

      <D />
      <SectionHeading>Limitation of Liability</SectionHeading>
      <P>To the maximum extent permitted by law, LookThroughProfits, Inc. and its officers, directors, employees, contractors, affiliates, and agents will not be liable for any indirect, incidental, special, consequential, exemplary, or punitive damages, or for any loss of profits, revenue, data, goodwill, or business interruption, arising out of or related to your use of (or inability to use) the Service, even if we have been advised of the possibility of such damages.</P>
      <P>In all cases, LookThroughProfits, Inc.&rsquo;s total liability arising out of or related to these Terms or the Service will not exceed the greater of (a) the amount you paid to us for the Service in the 12 months immediately preceding the event giving rise to the claim or (b) USD $100.</P>
      <P>Some jurisdictions do not allow the exclusion or limitation of certain damages or warranties, so some of the above limitations may not apply to you. Nothing in these Terms excludes or limits liability that cannot be excluded or limited under applicable law (for example, liability for gross negligence or willful misconduct where such limitation is prohibited).</P>

      <D />
      <SectionHeading>Indemnification</SectionHeading>
      <P>You agree to defend, indemnify, and hold harmless LookThroughProfits, Inc. and its officers, directors, employees, contractors, affiliates, and agents from and against any claims, liabilities, damages, losses, and expenses (including reasonable attorneys&rsquo; fees) arising out of or related to:</P>
      <Bullets items={[
        "Your use of the Service;",
        "Your violation of these Terms;",
        "Your violation of any law or third-party right; or",
        "Any content or data you provide, submit, or authorize for access through the Service.",
      ]} />
      <P>We reserve the right to assume the exclusive defense and control of any matter subject to indemnification, and you agree to cooperate with our defense.</P>

      <D />
      <SectionHeading>Dispute Resolution, Governing Law, and Venue</SectionHeading>

      <SubHeading>Governing law</SubHeading>
      <P>Except as restricted by applicable law (including mandatory consumer protection laws), these Terms are governed by the laws of the State of Delaware, without regard to conflict-of-laws principles.</P>

      <SubHeading>Venue</SubHeading>
      <P>Except where prohibited by applicable law, you agree that any dispute, claim, or controversy arising out of or relating to these Terms or the Service will be brought exclusively in the state or federal courts located in Delaware, and you consent to personal jurisdiction in those courts.</P>

      <SubHeading>Mandatory consumer rights preserved</SubHeading>
      <P>Nothing in these Terms is intended to waive consumer statutory rights that cannot be waived under applicable law.</P>
      <P><strong>Qu&eacute;bec consumers:</strong> Certain contract terms (including mandatory arbitration clauses, certain restrictions on class actions, and foreign choice-of-law clauses) may be prohibited for consumer contracts, and rules may apply to unilateral amendments and cancellation rights. To the extent Qu&eacute;bec consumer protection law applies, the relevant mandatory provisions control.</P>
      <P><strong>Ontario consumers:</strong> Ontario consumer protection law limits the enforceability of terms that require arbitration in a way that prevents consumers from commencing certain court actions and preserves consumers&rsquo; ability to participate in class proceedings despite contractual terms to the contrary. To the extent Ontario consumer protection law applies, the relevant mandatory provisions control.</P>

      <D />
      <SectionHeading>Changes to These Terms</SectionHeading>
      <P>We may update these Terms from time to time. If we make material changes, we will provide reasonable notice (for example, by posting notice on the Website or by emailing account holders). Your continued use of the Service after the effective date of the updated Terms constitutes your acceptance, to the extent permitted by law.</P>
      <P>If you do not agree to the updated Terms, you must stop using the Service and cancel your subscription.</P>

      <D />
      <SectionHeading>Miscellaneous</SectionHeading>
      <Bullets items={[
        <><strong>Entire agreement.</strong> These Terms (together with any policies they incorporate by reference) constitute the entire agreement between you and us regarding the Service and supersede any prior agreements or understandings.</>,
        <><strong>Severability.</strong> If any provision is held invalid or unenforceable, the remaining provisions remain in effect, and the invalid provision will be modified to the minimum extent necessary to make it enforceable.</>,
        <><strong>No waiver.</strong> Our failure to enforce any right or provision is not a waiver of that right or provision.</>,
        <><strong>Assignment.</strong> You may not assign these Terms without our prior written consent. We may assign these Terms in connection with a merger, acquisition, corporate reorganization, or sale of all or substantially all assets.</>,
        <><strong>Headings.</strong> Headings are for convenience only and do not affect interpretation.</>,
      ]} />

      <D />
      <SectionHeading>Contact Us</SectionHeading>
      <Box
        sx={{
          mt: "1rem",
          p: "1.25rem 1.5rem",
          background: "#f8f9fb",
          border: "1px solid #dde1e7",
          borderLeft: `4px solid ${NAVY}`,
        }}
      >
        <Box sx={{ fontSize: FS - 0.5, fontWeight: 700, color: NAVY, letterSpacing: "0.02em", mb: "0.35rem" }}>
          LookThroughProfits, Inc. &mdash; Legal / Terms of Use
        </Box>
        <Box sx={{ fontSize: FS - 0.5, color: SUBTLE, lineHeight: 1.8 }}>
          169 Madison Ave STE 38180<br />
          New York, NY 10016, United States
        </Box>
        <Box sx={{ mt: "0.6rem" }}>
          <A href="mailto:howard@stockownerreport.com">howard@stockownerreport.com</A>
        </Box>
      </Box>

    </LegalDocumentLayout>
  );
}
